apiVersion: batch/v1
kind: Job
metadata:
  name: builder
  namespace: job
spec:
  template:
    spec:
      containers:
      - name: builder
        image: python:alpine
        volumeMounts:
        - mountPath: /workspace
          name: source
        command: ['python', 'workspace/main.py']
      volumes:
      - name: source
        hostPath:
          # directory location on host
          path: /host/ubuntu_root/workspace/helm_editor/source/
          # this field is optional
          type: Directory
      restartPolicy: Never
  backoffLimit: 4
